### PR TITLE
Make compatible with arm64 brew, test on older and latest macos, strip away no longer needed windows test env exclusion

### PR DESCRIPTION
**Pull request by yarikoptic**
expecting that macos-latest testing would not succeed. We might want to add explicitly `macos-12` and then new `macos-latest` which would be arm

### CODE REVIEW

**Comment by yarikoptic** [comment]
dropped TEMP commit, force pushed, adjusted title to reflect included changes, marking for release.

**Comment by mslw** [comment]
@yarikoptic the release action crashed - what on earth happened there? https://github.com/datalad/datalad-installer/actions/runs/8834788909/job/24257350453

**Comment by yarikoptic** [comment]
merged my "fix" #198 , waiting on result

**Comment by mslw** [comment]
I also just realized that the version was simply pinned - I'll keep my fingers crossed :crossed_fingers:

**Comment by yarikoptic** [comment]
FWIW -- 1.0.5 was just released so all is good. I am rerunning brew job I had https://github.com/datalad/datalad/actions/runs/8820905835?pr=7586 in https://github.com/datalad/datalad/pull/7586 which if passes is IMHO worth merging to get us 1 step closer there

**Pull request merged**
