### PR TITLE
Support installing git-annex-remote-rclone via Conda

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
note: appveyor isn't happy

**Comment by jwodder** [comment]
@yarikoptic The Appveyor issue is likely the same one as from #140; merging that one and then rebasing this one should fix everything.

**Comment by yarikoptic** [comment]
merged that one, please rebase. Cheers!

**Comment by jwodder** [comment]
@yarikoptic Rebased.

**Pull request merged**
