### PR TITLE
rclone -m downloads.rclone.org: Add bin_dir to PATH if necessary

### LINKED ISSUE #138: installation of rclone into a directory not within PATH should add PATH modification to env file
```
❯ datalad-installer -E ~/bin/rclones/1.59.2.sh rclone=v1.59.2 -m downloads.rclone.org --bin-dir ~/bin/rclones/1.59.2
2022-12-21T12:09:51-0500 [INFO    ] datalad_installer Installing rclone from downloads.rclone.org
2022-12-21T12:09:51-0500 [INFO    ] datalad_installer Version: v1.59.2
2022-12-21T12:09:51-0500 [INFO    ] datalad_installer Bin dir: /home/yoh/bin/rclones/1.59.2
2022-12-21T12:09:51-0500 [INFO    ] datalad_installer Man dir: None
2022-12-21T12:09:51-0500 [INFO    ] datalad_installer Downloading https://downloads.rclone.org/v1.59.2/rclone-v1.59.2-linux-amd64.zip
2022-12-21T12:09:55-0500 [INFO    ] datalad_installer Moving /home/yoh/.tmp/tmpt9by08zs/rclone-v1.59.2-linux-amd64/rclone to /home/yoh/bin/rclones/1.59.2/rclone
2022-12-21T12:09:55-0500 [INFO    ] datalad_installer rclone is now installed at /home/yoh/bin/rclones/1.59.2/rclone
❯ cat ~/bin/rclones/1.59.2.sh
```

and I was expecting that `~/bin/rclones/1.59.2.sh` would contain 

```shell
export PATH=~/bin/rclones/1.59.2/:$PATH
```

as I believe do similarly for miniconda etc

### PR DESCRIPTION
**Pull request by jwodder**
Closes #138.

### CODE REVIEW

**Comment by yarikoptic** [comment]
I merged other PRs, could you please rebase so we could see clean CI run?

**Comment by jwodder** [comment]
@yarikoptic Rebased.

**Comment by yarikoptic** [comment]
appveyor remains red due to mac... pushed a commit to switch to macos-monterey, let's see

**Comment by yarikoptic** [comment]
green -- let's proceed!

**Pull request merged**
