### PR TITLE
Add a test of installing git-annex with brew on macOS

### LINKED ISSUE #53: Add a test which would cause testing of brew install
according to coverage report (for me it is all red ATM) of #51 , we have no unittest which would test brew installation.

If brew is a default for OSX (if brew is available), may be it could be a nice generic `datalad_installer.py --sudo=ok git-annex`? if not, could be crafted to force `brew`.

may be to be done before the fix for #52 is merged to see if may be we replicate the need.

### PR DESCRIPTION
**Pull request by jwodder**
Closes #53.

### CODE REVIEW

**Comment by yarikoptic** [comment]
<details>
<summary>in a sample (3.9) I looked at it seems to install git-annex but then fail with something else after</summary> 

```shell
2021-04-15T16:44:19.2361370Z ==> Summary
2021-04-15T16:44:19.2362160Z 🍺  /usr/local/Cellar/quvi/0.4.2: 9 files, 125.5KB
2021-04-15T16:44:19.2362960Z ==> Installing git-annex
2021-04-15T16:44:19.2364020Z ==> Pouring git-annex--8.20210310.catalina.bottle.tar.gz
2021-04-15T16:44:19.2364680Z You can try again using:
2021-04-15T16:44:19.2365470Z   brew postinstall git-annex
2021-04-15T16:44:19.2365860Z ==> Caveats
2021-04-15T16:44:19.2366700Z To have launchd start git-annex now and restart at login:
2021-04-15T16:44:19.2368230Z   brew services start git-annex
2021-04-15T16:44:19.2369170Z Or, if you don't want/need a background service you can just run:
2021-04-15T16:44:19.2370070Z   git annex assistant --autostart
2021-04-15T16:44:19.2370630Z ==> Summary
2021-04-15T16:44:19.2371500Z 🍺  /usr/local/Cellar/git-annex/8.20210310: 9 files, 59.7MB
2021-04-15T16:44:19.2371940Z ==> Caveats
2021-04-15T16:44:19.2372230Z ==> lua@5.1
2021-04-15T16:44:19.2372570Z You may also want luarocks:
2021-04-15T16:44:19.2372970Z   brew install luarocks
2021-04-15T16:44:19.2373680Z ==> git-annex
2021-04-15T16:44:19.2374540Z To have launchd start git-annex now and restart at login:
2021-04-15T16:44:19.2375490Z   brew services start git-annex
2021-04-15T16:44:19.2376540Z Or, if you don't want/need a background service you can just run:
2021-04-15T16:44:19.2377450Z   git annex assistant --autostart
2021-04-15T16:44:19.2378460Z ----------------------------- Captured stderr call -----------------------------
2021-04-15T16:44:19.2379040Z Updating Homebrew...
2021-04-15T16:44:19.2379660Z ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
2021-04-15T16:44:19.2380490Z   https://github.com/Homebrew/brew#donations
2021-04-15T16:44:19.2381450Z ==> Auto-updated Homebrew!
2021-04-15T16:44:19.2382410Z Updated 4 taps (homebrew/core, homebrew/cask, mongodb/brew and aws/tap).
2021-04-15T16:44:19.2383030Z ==> Updated Formulae
2021-04-15T16:44:19.2383410Z Updated 175 formulae.
2021-04-15T16:44:19.2383770Z ==> Updated Casks
2021-04-15T16:44:19.2384120Z Updated 277 casks.
2021-04-15T16:44:19.2385430Z Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
2021-04-15T16:44:19.2386570Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2387880Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:19
2021-04-15T16:44:19.2388350Z 
2021-04-15T16:44:19.2389570Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2390680Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2391970Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:20
2021-04-15T16:44:19.2392450Z 
2021-04-15T16:44:19.2393650Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2394750Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2396020Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:21
2021-04-15T16:44:19.2396500Z 
2021-04-15T16:44:19.2397710Z Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
2021-04-15T16:44:19.2398830Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2400160Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-rc.rb:19
2021-04-15T16:44:19.2400650Z 
2021-04-15T16:44:19.2401850Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2403060Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2404590Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-rc.rb:20
2021-04-15T16:44:19.2405090Z 
2021-04-15T16:44:19.2406290Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2407890Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2409410Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-rc.rb:21
2021-04-15T16:44:19.2409910Z 
2021-04-15T16:44:19.2411100Z Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
2021-04-15T16:44:19.2412180Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2413560Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-nightly.rb:17
2021-04-15T16:44:19.2414090Z 
2021-04-15T16:44:19.2415480Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2416590Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2418380Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-nightly.rb:18
2021-04-15T16:44:19.2418970Z 
2021-04-15T16:44:19.2420180Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2421260Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2422560Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-nightly.rb:19
2021-04-15T16:44:19.2423100Z 
2021-04-15T16:44:19.2423290Z 
2021-04-15T16:44:19.2423780Z Warning: lua@5.1 has been deprecated because it is not supported upstream!
2021-04-15T16:44:19.2424860Z Warning: The post-install step did not complete successfully
2021-04-15T16:44:19.2425930Z Warning: The post-install step did not complete successfully
2021-04-15T16:44:19.2426990Z Warning: The post-install step did not complete successfully
2021-04-15T16:44:19.2428040Z Warning: The post-install step did not complete successfully
2021-04-15T16:44:19.2429110Z Warning: The post-install step did not complete successfully
2021-04-15T16:44:19.2430150Z Warning: The post-install step did not complete successfully
2021-04-15T16:44:19.2431550Z Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
2021-04-15T16:44:19.2432630Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2433880Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:19
2021-04-15T16:44:19.2434350Z 
2021-04-15T16:44:19.2435570Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2436830Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2438260Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:20
2021-04-15T16:44:19.2438740Z 
2021-04-15T16:44:19.2439910Z Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
2021-04-15T16:44:19.2440990Z Please report this issue to the aws/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
2021-04-15T16:44:19.2442240Z   /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli.rb:21
2021-04-15T16:44:19.2442700Z 
```
</details>

**Comment by jwodder** [comment]
@yarikoptic I have an idea what's causing the failure, and [I've posted a question on the Homebrew repository](https://github.com/Homebrew/discussions/discussions/1313).

**Comment by jwodder** [comment]
@yarikoptic The tests pass now.

**Comment by yarikoptic** [comment]
WOOHOO! Thank you @jwodder !

**Pull request merged**
